version: '3.8'

services:
  server:
    ports:
      - "3001:3001"
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    ports:
      - "3000:3000"
    depends_on:
      - server
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
